-- MySQL Script generated by MySQL Workbench
-- ter 27 jul 2021 16:23:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pdz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pdz` ;

-- -----------------------------------------------------
-- Schema pdz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdz` ;
USE `pdz` ;

-- -----------------------------------------------------
-- Table `pdz`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdz`.`produto` ;

CREATE TABLE IF NOT EXISTS `pdz`.`produto` (
  `id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NULL,
  `valor_unitario` DECIMAL(10,3) NULL,
  `unidade_medida` CHAR(5) NULL,
  `peso` DECIMAL(10,3) NULL,
  `quantidade` DECIMAL(10,3) NULL,
  `quantidade_estoque` DECIMAL(10,3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdz`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdz`.`venda` ;

CREATE TABLE IF NOT EXISTS `pdz`.`venda` (
  `id` INT UNSIGNED NOT NULL,
  `quantidade_produtos` DECIMAL(10,3) NULL,
  `valor_venda` DECIMAL(10,3) NULL,
  `valor_pago` DECIMAL(10,3) NULL,
  `valor_troco` DECIMAL(10,3) NULL,
  `status venda` INT NULL,
  `forma_pagamento` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdz`.`item_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdz`.`item_venda` ;

CREATE TABLE IF NOT EXISTS `pdz`.`item_venda` (
  `id` INT NOT NULL,
  `produto_id` INT UNSIGNED NOT NULL,
  `venda_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_venda_produto_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_item_venda_venda1_idx` (`venda_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_venda_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `pdz`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `pdz`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
